### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Quantummatic** [kevinjycui/DesmosBezierRenderer#17] opened 2021-05-22 05:08 UTC
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "backend.py", line 87, in get_expressions
    for expr in get_latex(FRAME_DIR + '/frame%d.%s' % (frame+1, FILE_EXT)):
  File "backend.py", line 62, in get_latex
    path = get_trace(get_contours(filename))
  File "backend.py", line 36, in get_contours
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-ms668fyv/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "backend.py", line 107, in <module>
    frame_latex = pool.map(get_expressions, frame_latex)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-ms668fyv/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by Quantummatic** [comment] 2021-05-22 05:09
For some reason, when I try to render a single image this happens.

**Comment by Atlae** [comment] 2021-05-23 07:48
I got the same error when I was trying to draw a JPG file when backend.py had specified PNG. Could that be the issue?

**Comment by kevinjycui** [comment] 2021-05-26 20:47
This is a duplicate of #5. It just means that for some reason the program is unable to read the image file. It could be an issue with how you named the file, where you saved it, or the file's permissions. How do you have the file saved?

**Comment by Quantummatic** [comment] 2021-05-27 21:57
> This is a duplicate of #5. It just means that for some reason the program is unable to read the image file. It could be an issue with how you named the file, where you saved it, or the file's permissions. How do you have the file saved?

The file was originally a JPG file, with it being changed to PNG. Is that a possible reason?

**Comment by Atlae** [comment] 2021-05-27 22:48
What do you mean by "changed to a PNG?" Did you use a converter or did you just change the file extension to PNG?

**Comment by Atlae** [comment] 2021-05-27 23:00
I just converted a JPG to a PNG, renamed it "frame1.png," and it worked fine for me. From my own experience, it could be a couple of things. When I copy a Windows file to WSL it creates a "Zone Identifier" which can break it. Or maybe it wasn't converted correctly. But something's up with the file at the very least

**Closed** 2021-06-06 01:38 UTC

**Comment by Green-Thanos** [comment] 2021-06-06 22:07
Im on a mac, and my case was there was a system file named .DS_Store automatically generated in my frames folder. I fixed it just by deleting it. If you notice the number of frames the script prints out is different from the number of frames you intended, maybe thats the issue
