### ISSUE TITLE
Error Running backend

### ISSUE THREAD

**Issue by MR-Spagetty** [kevinjycui/DesmosBezierRenderer#42] opened 2022-05-06 06:34 UTC
i have been trying to run the backen to render a single immage but keep getting this error:
```
Desmos Bezier Renderer
Junferno 2021
https://github.com/kevinjycui/DesmosBezierRenderer
-----------------------------
Processing 2 frames... Please wait for processing to finish before running on frontend

[ WARN:0@0.175] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('frames/frame2.png'): can't open/read file: check file path/integrity
--> Frame 1/2[ERROR] Unable to process one or more files. Remember image files should be named <DIRECTORY>/frame<INDEX>.<EXTENSION> where INDEX represents the frame number starting from 1 and DIRECTORY and EXTENSION are defined by command line arguments (e.g. frames/frame1.png). Please check if:
        The files exist
        The files are all valid image files
        The name of the files given is correct as per command line arguments
        The program has the necessary permissions to read the file.

Use backend.py -h for further documentation

-----------------------------
Full error traceback:

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "backend.py", line 118, in get_expressions
    for expr in get_latex(FRAME_DIR + '/frame%d.%s' % (frame+1, FILE_EXT)):
  File "backend.py", line 92, in get_latex
    path = get_trace(get_contours(filename))
  File "backend.py", line 62, in get_contours
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "backend.py", line 208, in <module>
    frame_latex = pool.map(get_expressions, frame_latex)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```
the image i am trying to render is:
![frame1](https://user-images.githubusercontent.com/54694556/167079367-0792e0a2-1697-4706-a3bb-271d7131ac0a.png)

**Comment by orion-t** [comment] 2022-06-26 19:03
same

**Comment by kevinjycui** [comment] 2022-08-07 22:30
Sorry for the incredibly late response, though this seems to be a duplicate of #27 
Closing the issue for now, feel free to open if you're still working on this.

**Closed by kevinjycui** 2022-08-07 22:30 UTC

**Comment by PixelArt77** [comment] 2024-02-22 23:31
Hello, 

I am having the same issue. cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

I tried everything so far that was close to this problem. The file is named correctly, but it still can't see it. 

Could you please help? @kevinjycui

**Comment by kevinjycui** [comment] 2024-02-23 20:32
> Hello,
> 
> I am having the same issue. cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
> 
> I tried everything so far that was close to this problem. The file is named correctly, but it still can't see it.
> 
> Could you please help? @kevinjycui

The error is a general error in which the program cannot find or see the file. Either the file does not exist, the name of the file given is incorrect (check directory and file extension), or the program does have the necessary permissions to read the file.

**Comment by PixelArt77** [comment] 2024-02-27 19:09
Thank youu!! It works now
