### ISSUE TITLE
Problem when i run backend.py

### ISSUE THREAD

**Issue by Gyro-Gyro** [kevinjycui/DesmosBezierRenderer#27] opened 2021-08-12 11:23 UTC
whenever i try to run backend.py i get the following error:

Desmos Bezier Renderer
Junferno 2021
https://github.com/kevinjycui/DesmosBezierRenderer
-----------------------------
Processing 1 frames... Please wait for processing to finish before running on frontend

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "backend.py", line 87, in get_expressions
    for expr in get_latex(FRAME_DIR + '/frame%d.%s' % (frame+1, FILE_EXT)):
  File "backend.py", line 62, in get_latex
    path = get_trace(get_contours(filename))
  File "backend.py", line 36, in get_contours
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-ms668fyv/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "backend.py", line 108, in <module>
    frame_latex = pool.map(get_expressions, frame_latex)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-ms668fyv/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

ive installed all the dependencies and did a fresh restart of the entire process a few times.
im using a linux mint virtual machine

**Comment by mchen0037** [comment] 2021-09-05 05:51
+1

**Comment by kevinjycui** [comment] 2021-09-17 20:08
This is a duplicate of #5, #12, #17

The error is a general error in which the program cannot find or see the file. Either the file does not exist, the name of the file given is incorrect (check directory and file extension), or the program does have the necessary permissions to read the file. I apologise for the late reply. Please re-open this issue if you're still working on this.

**Closed by kevinjycui** 2021-09-17 20:08 UTC

**Comment by Maxxxutko** [comment] 2022-02-15 06:56
I'm running all processes in su mode, I mentioned full path to the frame folder in backend.py. Can it be due to using .bmp files?
