### ISSUE TITLE
error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

### ISSUE THREAD

**Issue by FireClaw39** [kevinjycui/DesmosBezierRenderer#39] opened 2022-03-04 15:36 UTC
Hey, I have the path at frames\frame%d.png, but it still isn't working. Everything is a png. Everything is in "frames". IDK what's wrong with it.
 
`Traceback (most recent call last):

  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))

  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))

  File "backend.py", line 118, in get_expressions
    for expr in get_latex(FRAME_DIR + '/frame%d.%s' % (frame+1, FILE_EXT)):

  File "backend.py", line 92, in get_latex
    path = get_trace(get_contours(filename))
 
 File "backend.py", line 62, in get_contours
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-ms668fyv/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'`

**Comment by FireClaw39** [comment] 2022-03-04 17:18
I don't know much about coding if this is an obvious answer lol

**Comment by kevinjycui** [comment] 2022-03-04 21:50
This is a duplicate of #27 
Have you checked the solution in that issue?

**Comment by FireClaw39** [comment] 2022-03-04 22:01
Yes

**Comment by kevinjycui** [comment] 2022-03-04 22:52
Can you show me what command you are running and also the structure of your directory (including within the frame subdirectory)?

**Comment by FireClaw39** [comment] 2022-03-05 00:12
I am using `python3 backend.py

I primarily copied and pasted everything in order except I used sudo and upgraded numpy. 

`(env) fireclaw@Home-PC:~/DesmosBezierRenderer$ ls
1]                    LICENSE    backend.py  frames  index.html  nano.save.1
DesmosBezierRenderer  README.md  env         github  nano.save   requirements.txt`

Is that  the structure directory? (I am so sorry for my ignorance)

When I use ls /DesmosBezierRenderer/frames, all the frames pop up as it should be named Ex: `frame1.png` so...I spoke with a computer science teacher and she said that my computer may be incompatible?

**Comment by kevinjycui** [comment] 2022-03-05 01:56
This issue should be with the file itself, rather than the system. You should be 100% sure that the files are valid PNG files and the program has permission to read them. Try adding the following statement before line 118 in backend.py and let me know what it outputs:
```python
path1 = FRAME_DIR + '/frame%d.%s' % (frame+1, FILE_EXT)
print(path1, "exists" if os.path.exists(path1) else "does not exist")
```

**Comment by FireClaw39** [comment] 2022-03-05 17:47
It says the same thing

**Comment by kevinjycui** [comment] 2022-03-05 23:29
What does the print statement output though? Find the line of output where it says "exists" or "does not exist" (it should be before the error happens).

**Comment by kevinjycui** [comment] 2022-03-05 23:29
Sorry for the complicated process. I'm unable to reproduce this error since it's specific to your file and your file system.

**Comment by FireClaw39** [comment] 2022-03-06 04:07
Ah, well the problem occurs in get_traces which is before get_expressions, so I don't think it gets that far?
`Traceback (most recent call last):

  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))

  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))

  File "backend.py", line 120, in get_expressions
    for expr in get_latex(FRAME_DIR + '/frame%d.%s' % (frame+1, FILE_EXT)):
 
 File "backend.py", line 92, in get_latex
    path = get_trace(get_contours(filename))

  File "backend.py", line 62, in get_contours
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-ms668fyv/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'`

I am thinking that maybe because I copied and pasted all the images from my OneDrive folder? I was thinking of redownloading everything directly to the directory rather than using a copy from the online folder, but I don't really know if that's a problem. Should I try that or does that not matter since I made copies of the files?

**Comment by FireClaw39** [comment] 2022-03-06 04:07
I went into one file, edited it slightly and resaved it directly to the frames file to see if this was the problem, but it still gave the same results, but I thought I should ask you anyways cuz I don't actually know what I'm doing lol.

**Comment by FireClaw39** [comment] 2022-03-06 17:05
So, I put the line above gray = cv2 in get_contours, and saved it as backend2.py and this is what it outputted

'(env) fireclaw@Home-PC:~/DesmosBezierRenderer$ python backend2.py
Desmos Bezier Renderer
Junferno 2021
https://github.com/kevinjycui/DesmosBezierRenderer
-------
Processing 102 frames... Please wait for processing to finish before running on frontend

frames/frame1.png exists
frames/frame8.png exists
frames/frame15.png exists
frames/frame22.png exists
frames/frame29.png exists
frames/frame36.png exists
frames/frame43.png exists
frames/frame50.png exists
frames/frame57.png exists
frames/frame64.png exists
frames/frame71.png exists
frames/frame78.png exists
frames/frame85.png exists
frames/frame92.png exists
frames/frame99.png exists
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "backend2.py", line 121, in get_expressions
    for expr in get_latex(FRAME_DIR + '/frame%d.%s' % (frame+1, FILE_EXT)):
  File "backend2.py", line 93, in get_latex
    path = get_trace(get_contours(filename))
  File "backend2.py", line 61, in get_contours
    path1 = FRAME_DIR + '/frame%d.%s' % (frame+1, FILE_EXT)
TypeError: unsupported operand type(s) for +: 'Synchronized' and 'int'`

**Comment by FireClaw39** [comment] 2022-03-06 17:12
So....it's saying that all the frames besides the one listed above are invalid? But they're named the same way?

**Comment by FireClaw39** [comment] 2022-03-06 17:32
So, I looked up the permissions. 
For the Bezier Renderer regarding frames:
`drwxr-xr-x 1 fireclaw fireclaw  4096 Mar  6 12:19 frames` 
 
For backend.py
`(env) fireclaw@Home-PC:~/DesmosBezierRenderer$ ls -l backend.py
-rw-r--r-- 1 fireclaw fireclaw 8406 Mar  5 12:46 backend.py`

**Comment by kevinjycui** [comment] 2022-03-06 20:00
The listing is behaving as intended. The program won't go image by image but jump frames as an optimization. Maybe it's an issue with the images? What happens if you try rendering a different image? Make a directory called `test` and copy and paste `github/sample.png` as `test/frame1.png` and then try running `python3 backend.py -f test`.

**Comment by FireClaw39** [comment] 2022-03-06 21:00
`Processing 1 frames... Please wait for processing to finish before running on frontend

test/frame1.png exists
[ERROR] Unable to process one or more files. Remember image files should be named <DIRECTORY>/frame<INDEX>.<EXTENSION> where INDEX represents the frame number starting from 1 and DIRECTORY and EXTENSION are defined by command line arguments (e.g. frames/frame1.png). Please check if:
        The files exist
        The files are all valid image files
        The name of the files given is correct as per command line arguments
        The program has the necessary permissions to read the file.`
Same error with cvtcolor.

**Comment by kevinjycui** [comment] 2022-03-06 21:06
Hmm... I'm really confused. Maybe it's still a permission issue? This is a bit of a reach but what happens when you run `sudo python3 backend.py -f test`
?

**Comment by FireClaw39** [comment] 2022-03-06 21:09
I tried that with the original command as well already. 
It gives me this output
`Traceback (most recent call last):
  File "backend.py", line 8, in <module>
    import potrace
  File "/usr/local/lib/python3.8/dist-packages/potrace/__init__.py", line 1, in <module>
    from potrace._potrace import *  # NOQA
  File "potrace/_potrace.pyx", line 1, in init potrace._potrace
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

I already upgraded numpy, though.

**Comment by kevinjycui** [comment] 2022-03-06 21:12
That's probably because numpy is updated for you but not the sudo user. It was a reach anyway. I'll try reconfiguring the repo and playing around with it myself, but if it is an issue with your system, I'm not sure how else I could help at the moment.

**Comment by FireClaw39** [comment] 2022-03-06 21:15
I'll be discussing the problem with my computer science teacher tomorrow and going through the process again on a different computer. I'll let you know if I run into the same problem on that computer, I guess.

**Comment by FireClaw39** [comment] 2022-03-06 21:18
I reinstalled numpy with sudo, and it's running!

**Comment by FireClaw39** [comment] 2022-03-06 21:19
It's PROCESSING!! Life isn't so terrible after all, my gosh.

**Comment by FireClaw39** [comment] 2022-03-06 21:25
Alright, problem fixed, thanks

**Comment by kevinjycui** [comment] 2022-03-06 21:25
Yay! That probably means it *was* a permission issue then. If you want to run it without sudo, you could probably just try enabling all permissions on the frames directory (it's better practice anyway but it probably doesn't matter if you're just doing it once. Just a heads for the future though in case you need to enable all permissions on something):
```sh
chmod 777 frames
```
I wasn't sure if this was the way to go since it showed that you *did* have read permissions but I guess something else must've been off. Congratulations!

**Comment by FireClaw39** [comment] 2022-03-06 21:25
But um, basic question plz

**Comment by FireClaw39** [comment] 2022-03-06 21:26
Where do I load index html?

**Closed by kevinjycui** 2022-03-06 21:25 UTC

**Comment by kevinjycui** [comment] 2022-03-06 21:27
Copy the path of index.html (e.g. /home/username/DesmosBezierRenderer/index.html) and paste it in the search bar of any web browser!

**Comment by FireClaw39** [comment] 2022-03-06 21:29
Oh, thanks! I was just gonna look it up cuz I thought you left lol

**Comment by kevinjycui** [comment] 2022-03-06 22:18
If you're still there, you can `git pull` to get the latest changes in the repo (I just fixed some issues. This should allow you to render with better quality).

**Comment by FireClaw39** [comment] 2022-03-06 22:19
Okay! :D

**Comment by FireClaw39** [comment] 2022-03-07 22:38
Using a different computer, I found out that DesmosBezierRenderer was supposed to have these permissions today
`drwxrwxr-x 1` 
I had:
`drwxr-xr-x 1`

**Comment by FireClaw39** [comment] 2022-03-07 22:39
I thought I'd tell you :D
